import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'

import './globals.css'
import { Noto_Serif, Noto_Sans } from 'next/font/google'

import { ThemeProvider } from '@/components/theme-provider'
import AppLayout from '@/features/layout/composable/app-layout'
import { cn } from '@/lib/utils'

const notoSansHeading = Noto_Sans({ subsets: ['latin'], variable: '--font-heading' })

const notoSerif = Noto_Serif({ subsets: ['latin'], variable: '--font-serif' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={cn(
        'h-full',
        'antialiased',
        'font-serif',
        notoSerif.variable,
        notoSansHeading.variable,
      )}
    >
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextIntlClientProvider>
            <AppLayout>{children}</AppLayout>
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
